"""Add status column to Risk model

Revision ID: b2791367f0bc
Revises: 
Create Date: 2025-04-18 16:18:21.279855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2791367f0bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='Open'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
