"""Add treatment_plan field to Risk model

Revision ID: b620487d6fb4
Revises: b2791367f0bc
Create Date: 2025-04-24 11:19:25.522585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b620487d6fb4'
down_revision = 'b2791367f0bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treatment_plan', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk', schema=None) as batch_op:
        batch_op.drop_column('treatment_plan')

    # ### end Alembic commands ###
